Java.topics.registry = [
  {
    id: 'getting-started',
    title: 'Getting Started on Ubuntu',
    tagline: 'Install JDK 21 and run your first program',
    description: 'Use the Ubuntu terminal, apt, OpenJDK 21, javac, java, and a tiny folder layout before writing larger code.',
    path: 'topics/getting-started/index.html',
    status: 'available',
    tier: 'foundation',
    order: 1,
    prerequisites: [],
    ltsNote: 'Ubuntu + Java 21 LTS',
    stats: [{ value: '6', label: 'Lessons' }, { value: 'Ubuntu', label: 'OS' }],
    accent: 'amber'
  },
  {
    id: 'syntax-fundamentals',
    title: 'Syntax Fundamentals',
    tagline: 'The grammar every Java file shares',
    description: 'Semicolons, blocks, comments, identifiers, naming conventions, packages, and imports without assuming prior Java.',
    path: 'topics/syntax-fundamentals/index.html',
    status: 'available',
    tier: 'foundation',
    order: 2,
    prerequisites: ['getting-started'],
    ltsNote: 'Java 21 LTS',
    stats: [{ value: '6', label: 'Lessons' }, { value: 'Core', label: 'Level' }],
    accent: 'teal'
  },
  {
    id: 'types-and-variables',
    title: 'Types & Variables',
    tagline: 'Values, names, scope, and conversion',
    description: 'Primitives, String, literals, var, casting, final, scope, and the first stack/heap/reference mental model.',
    path: 'topics/types-and-variables/index.html',
    status: 'available',
    tier: 'foundation',
    order: 3,
    prerequisites: ['syntax-fundamentals'],
    ltsNote: 'Java 21 LTS',
    stats: [{ value: '9', label: 'Lessons' }, { value: 'Core', label: 'Level' }],
    accent: 'coral'
  },
  {
    id: 'operators',
    title: 'Operators',
    tagline: 'How expressions calculate and compare',
    description: 'Arithmetic, assignment, comparison, logical operators, bitwise basics, precedence, and short-circuiting.',
    path: 'topics/operators/index.html',
    status: 'available',
    tier: 'foundation',
    order: 4,
    prerequisites: ['types-and-variables'],
    ltsNote: 'Java 21 LTS',
    stats: [{ value: '6', label: 'Lessons' }, { value: 'Core', label: 'Level' }],
    accent: 'violet'
  },
  {
    id: 'control-flow',
    title: 'Control Flow',
    tagline: 'Make programs choose and repeat',
    description: 'if/else, switch statements and expressions, for loops, enhanced for, while, do-while, break, and continue.',
    path: 'topics/control-flow/index.html',
    status: 'available',
    tier: 'foundation',
    order: 5,
    prerequisites: ['operators'],
    ltsNote: 'Java 21 LTS',
    stats: [{ value: '7', label: 'Lessons' }, { value: 'Core', label: 'Level' }],
    accent: 'amber'
  },
  {
    id: 'methods',
    title: 'Methods',
    tagline: 'Name reusable behavior',
    description: 'Declare methods, pass parameters, return values, overload safely, and keep beginner code readable.',
    path: 'topics/methods/index.html',
    status: 'available',
    tier: 'foundation',
    order: 6,
    prerequisites: ['control-flow'],
    ltsNote: 'Java 21 LTS',
    stats: [{ value: '3', label: 'Lessons' }, { value: 'Core', label: 'Level' }],
    accent: 'teal'
  },
  {
    id: 'classes-and-objects',
    title: 'Classes & Objects',
    tagline: 'Model state and behavior together',
    description: 'Fields, constructors, this, access modifiers, static vs instance members, records, and object references.',
    path: 'topics/classes-and-objects/index.html',
    status: 'available',
    tier: 'foundation',
    order: 7,
    prerequisites: ['methods'],
    ltsNote: 'Java 21 LTS',
    stats: [{ value: '3', label: 'Lessons' }, { value: 'OOP', label: 'Level' }],
    accent: 'coral'
  },
  {
    id: 'arrays',
    title: 'Arrays',
    tagline: 'Fixed-size sequences',
    description: 'Declare arrays, index safely, loop over values, and understand when fixed-size storage is enough.',
    path: 'topics/arrays/index.html',
    status: 'available',
    tier: 'foundation',
    order: 8,
    prerequisites: ['control-flow'],
    ltsNote: 'Java 21 LTS',
    stats: [{ value: '3', label: 'Lessons' }, { value: 'Core', label: 'Level' }],
    accent: 'teal'
  },
  {
    id: 'strings',
    title: 'Strings & Text',
    tagline: 'Work safely with text',
    description: 'String immutability, equality, common methods, formatting, text blocks, and StringBuilder.',
    path: 'topics/strings/index.html',
    status: 'available',
    tier: 'foundation',
    order: 9,
    prerequisites: ['types-and-variables', 'methods'],
    ltsNote: 'Java 21 LTS',
    stats: [{ value: '3', label: 'Lessons' }, { value: 'Text', label: 'Level' }],
    accent: 'coral'
  },
  {
    id: 'collections',
    title: 'Collections',
    tagline: 'Lists, sets, maps, and generics',
    description: 'Use ArrayList, HashSet, HashMap, enhanced for loops, and generics for flexible groups of objects.',
    path: 'topics/collections/index.html',
    status: 'available',
    tier: 'core',
    order: 10,
    prerequisites: ['arrays', 'classes-and-objects'],
    ltsNote: 'Java 21 LTS',
    stats: [{ value: '3', label: 'Lessons' }, { value: 'Core', label: 'Level' }],
    accent: 'violet'
  },
  {
    id: 'exceptions',
    title: 'Exceptions',
    tagline: 'Handle failures without hiding them',
    description: 'Use try/catch/finally, checked and unchecked exceptions, throw, and beginner-friendly failure boundaries.',
    path: 'topics/exceptions/index.html',
    status: 'available',
    tier: 'core',
    order: 11,
    prerequisites: ['methods', 'classes-and-objects'],
    ltsNote: 'Java 21 LTS',
    stats: [{ value: '3', label: 'Lessons' }, { value: 'Reliability', label: 'Level' }],
    accent: 'amber'
  },
  {
    id: 'io-basics',
    title: 'I/O Basics',
    tagline: 'Read input and files',
    description: 'Use Scanner, System.in/out, Path, Files, writing text, and try-with-resources on Ubuntu.',
    path: 'topics/io-basics/index.html',
    status: 'available',
    tier: 'core',
    order: 12,
    prerequisites: ['exceptions', 'strings'],
    ltsNote: 'Java 21 LTS',
    stats: [{ value: '3', label: 'Lessons' }, { value: 'Files', label: 'Level' }],
    accent: 'teal'
  },
  {
    id: 'debugging',
    title: 'Debugging',
    tagline: 'Find problems calmly',
    description: 'Read compiler errors, add temporary logging, use jshell, and start debugger-driven thinking from Ubuntu.',
    path: 'topics/debugging/index.html',
    status: 'available',
    tier: 'workflow',
    order: 13,
    prerequisites: ['io-basics'],
    ltsNote: 'Ubuntu terminal only',
    stats: [{ value: '3', label: 'Lessons' }, { value: 'Workflow', label: 'Level' }],
    accent: 'coral'
  },
  {
    id: 'testing',
    title: 'Testing',
    tagline: 'Prove behavior with small checks',
    description: 'Start with assertion-style checks, then learn the role of JUnit and repeatable test commands.',
    path: 'topics/testing/index.html',
    status: 'available',
    tier: 'workflow',
    order: 14,
    prerequisites: ['methods', 'classes-and-objects'],
    ltsNote: 'Ubuntu + Java 21 LTS',
    stats: [{ value: '3', label: 'Lessons' }, { value: 'Quality', label: 'Level' }],
    accent: 'violet'
  },
  {
    id: 'build-tools',
    title: 'Maven & Gradle Basics',
    tagline: 'Build repeatable Java projects',
    description: 'Understand project layout, dependencies, Maven commands, Gradle commands, and when to use each tool.',
    path: 'topics/build-tools/index.html',
    status: 'available',
    tier: 'workflow',
    order: 15,
    prerequisites: ['testing'],
    ltsNote: 'Ubuntu packages + Java 21',
    stats: [{ value: '3', label: 'Lessons' }, { value: 'Builds', label: 'Level' }],
    accent: 'amber'
  },
  {
    id: 'git-basics',
    title: 'Git Basics',
    tagline: 'Track, branch, merge, and recover code',
    description: 'Working tree, staging area, commits, branches, merges, remotes, pull requests, and safe undo workflows.',
    path: 'topics/git-basics/index.html',
    status: 'available',
    tier: 'workflow',
    order: 16,
    prerequisites: ['getting-started'],
    ltsNote: 'Ubuntu git workflow',
    stats: [{ value: '8', label: 'Lessons' }, { value: 'Git', label: 'Workflow' }],
    accent: 'violet'
  },
  {
    id: 'rest-and-http',
    title: 'REST & HTTP',
    tagline: 'Resources, methods, status codes, and contracts',
    description: 'Learn resources, endpoints, HTTP status codes, request bodies, idempotency, and the HTTP QUERY method from RFC 10008.',
    path: 'topics/rest-and-http/index.html',
    status: 'available',
    tier: 'applied',
    order: 17,
    prerequisites: ['collections', 'exceptions'],
    ltsNote: 'API foundation',
    stats: [{ value: '8', label: 'Lessons' }, { value: 'HTTP', label: 'APIs' }],
    accent: 'teal'
  },
  {
    id: 'uml-diagrams',
    title: 'UML Diagrams',
    tagline: 'Sketch software before building',
    description: 'Beginner-friendly class, sequence, state, activity, use case, and component diagrams for Java projects.',
    path: 'topics/uml-diagrams/index.html',
    status: 'available',
    tier: 'applied',
    order: 18,
    prerequisites: ['classes-and-objects'],
    ltsNote: 'Pairs well with Java OOP',
    stats: [{ value: '6', label: 'Diagrams' }, { value: 'UML', label: 'Modeling' }],
    accent: 'coral'
  },
  {
    id: 'jvm-memory',
    title: 'JVM & Memory',
    tagline: 'Understand what runs your code',
    description: 'Learn JVM, bytecode, class loading, stack, heap, references, garbage collection, and practical memory clues.',
    path: 'topics/jvm-memory/index.html',
    status: 'available',
    tier: 'advanced',
    order: 19,
    prerequisites: ['classes-and-objects', 'collections'],
    ltsNote: 'Java 21 LTS',
    stats: [{ value: '3', label: 'Lessons' }, { value: 'Runtime', label: 'Level' }],
    accent: 'amber'
  },
  {
    id: 'design-patterns',
    title: 'Design Patterns',
    tagline: '12 essential patterns with Java examples',
    description: 'Singleton to MVC: real-world analogies, when to use, pros and cons, and copy-ready Java examples.',
    path: 'topics/design-patterns/index.html',
    status: 'available',
    tier: 'advanced',
    order: 20,
    prerequisites: ['classes-and-objects', 'collections'],
    ltsNote: 'Examples stay within Java 21 LTS',
    stats: [{ value: '12', label: 'Patterns' }, { value: '4', label: 'Categories' }],
    accent: 'amber'
  },
  {
    id: 'practice-projects',
    title: 'Practice Projects',
    tagline: 'Turn lessons into small programs',
    description: 'Build tiny Ubuntu-terminal projects: calculator, grade book, file notes app, HTTP vocabulary quiz, and capstone ideas.',
    path: 'topics/practice-projects/index.html',
    status: 'available',
    tier: 'projects',
    order: 21,
    prerequisites: ['build-tools', 'git-basics'],
    ltsNote: 'Ubuntu terminal practice',
    stats: [{ value: '5', label: 'Projects' }, { value: 'Practice', label: 'Mode' }],
    accent: 'teal'
  }
];
