Java.glossary = [
  { term: 'abstract', definition: 'Java keyword for a class or method that is incomplete and must be extended or implemented before direct use.' },
  { term: 'assert', definition: 'Java keyword for a development-time check that can be enabled with java -ea.' },
  { term: 'boolean', definition: 'Primitive data type that stores true or false.' },
  { term: 'break', definition: 'Java keyword that exits a loop or switch early.' },
  { term: 'byte', definition: 'Primitive integer data type using 8 bits, from -128 to 127.' },
  { term: 'case', definition: 'Java keyword for one branch inside a switch.' },
  { term: 'catch', definition: 'Java keyword that handles an exception thrown by a try block.' },
  { term: 'char', definition: 'Primitive data type for one UTF-16 code unit, written with single quotes.' },
  { term: 'class', definition: 'Java keyword for a blueprint that defines fields, constructors, and methods.' },
  { term: 'const', definition: 'Reserved Java keyword that is not used. Use final for constants.' },
  { term: 'continue', definition: 'Java keyword that skips to the next loop iteration.' },
  { term: 'default', definition: 'Java keyword for a fallback switch branch or default interface method.' },
  { term: 'do', definition: 'Java keyword for a loop that runs the body before checking the condition.' },
  { term: 'double', definition: 'Primitive 64-bit floating-point data type for decimal numbers.' },
  { term: 'else', definition: 'Java keyword for the branch that runs when an if condition is false.' },
  { term: 'enum', definition: 'Java keyword for a fixed set of named values.' },
  { term: 'extends', definition: 'Java keyword that makes one class inherit from another class.' },
  { term: 'final', definition: 'Java keyword that prevents reassignment, overriding, or subclassing depending on where it is used.' },
  { term: 'finally', definition: 'Java keyword for cleanup code that runs after try/catch.' },
  { term: 'float', definition: 'Primitive 32-bit floating-point data type. Use double first as a beginner.' },
  { term: 'for', definition: 'Java keyword for counted loops and enhanced for-each loops.' },
  { term: 'goto', definition: 'Reserved Java keyword that is not used.' },
  { term: 'if', definition: 'Java keyword for running code only when a boolean condition is true.' },
  { term: 'implements', definition: 'Java keyword that says a class provides the methods required by an interface.' },
  { term: 'import', definition: 'Java keyword that lets a file use classes from another package by short name.' },
  { term: 'instanceof', definition: 'Java keyword that checks whether an object is compatible with a type.' },
  { term: 'int', definition: 'Primitive 32-bit integer data type, commonly used for whole numbers.' },
  { term: 'interface', definition: 'Java keyword for a contract of methods that classes can implement.' },
  { term: 'long', definition: 'Primitive 64-bit integer data type for large whole numbers.' },
  { term: 'native', definition: 'Java keyword for a method implemented outside Java, usually in platform-specific code.' },
  { term: 'new', definition: 'Java keyword that creates an object or array on the heap.' },
  { term: 'package', definition: 'Java keyword that declares the namespace a source file belongs to.' },
  { term: 'private', definition: 'Access modifier that allows use only inside the same class.' },
  { term: 'protected', definition: 'Access modifier visible to the same package and subclasses.' },
  { term: 'public', definition: 'Access modifier visible from anywhere that can access the package/module.' },
  { term: 'record', definition: 'Java keyword for a compact immutable data carrier class.' },
  { term: 'return', definition: 'Java keyword that exits a method and optionally sends a value back.' },
  { term: 'sealed', definition: 'Java keyword that restricts which classes may extend or implement a type.' },
  { term: 'short', definition: 'Primitive 16-bit integer data type.' },
  { term: 'static', definition: 'Java keyword for a member that belongs to the class, not to each object.' },
  { term: 'strictfp', definition: 'Java keyword related to older floating-point consistency rules; rarely needed in modern beginner code.' },
  { term: 'super', definition: 'Java keyword for accessing a superclass constructor, method, or field.' },
  { term: 'switch', definition: 'Java keyword for choosing among multiple cases.' },
  { term: 'synchronized', definition: 'Java keyword that protects a block or method so only one thread enters at a time.' },
  { term: 'this', definition: 'Java keyword for the current object.' },
  { term: 'throw', definition: 'Java keyword that raises an exception.' },
  { term: 'throws', definition: 'Java keyword that declares a method may pass an exception to its caller.' },
  { term: 'transient', definition: 'Java keyword that excludes a field from default serialization.' },
  { term: 'try', definition: 'Java keyword for code that might throw an exception.' },
  { term: 'var', definition: 'Java reserved type name that lets the compiler infer a local variable type.' },
  { term: 'void', definition: 'Java keyword meaning a method returns no value.' },
  { term: 'volatile', definition: 'Java keyword that makes field reads and writes visible across threads.' },
  { term: 'while', definition: 'Java keyword for loops that repeat while a boolean condition stays true.' },
  { term: 'String', definition: 'Reference type for text. Strings are immutable in Java.' },
  { term: 'ArrayList', definition: 'Resizable list implementation from java.util, useful when an array is too fixed.' },
  { term: 'HashMap', definition: 'Collection that stores key/value pairs for fast lookup by key.' },
  { term: 'HashSet', definition: 'Collection that stores unique values and ignores duplicates.' },
  { term: 'repository', definition: 'A project folder tracked by Git, including its hidden .git history.' },
  { term: 'working tree', definition: 'Your current files on disk before they are staged or committed.' },
  { term: 'staging area', definition: 'Git’s preparation area for the next commit.' },
  { term: 'commit', definition: 'A saved Git snapshot with a message and unique id.' },
  { term: 'branch', definition: 'A movable line of Git work used to isolate changes.' },
  { term: 'merge', definition: 'Git operation that combines changes from one branch into another.' },
  { term: 'remote', definition: 'A copy of a Git repository hosted somewhere else, such as GitHub.' },
  { term: 'pull request', definition: 'A review request to merge branch changes into another branch.' },
  { term: 'resource', definition: 'In REST, a thing your API exposes, such as /books or /orders/42.' },
  { term: 'endpoint', definition: 'A URL plus an HTTP method that a client can call.' },
  { term: 'GET', definition: 'HTTP method for reading a resource without changing it.' },
  { term: 'POST', definition: 'HTTP method often used to create a new resource or submit a command.' },
  { term: 'PUT', definition: 'HTTP method often used to replace a resource at a known URL.' },
  { term: 'PATCH', definition: 'HTTP method for a partial update.' },
  { term: 'DELETE', definition: 'HTTP method for removing a resource.' },
  { term: 'QUERY', definition: 'HTTP method from RFC 10008 for safe request-body queries.' },
  { term: 'status code', definition: 'Three-digit HTTP response number such as 200, 201, 400, or 404.' },
  { term: 'idempotent', definition: 'Safe to repeat with the same effect on server state.' },
  { term: 'class diagram', definition: 'UML diagram that shows classes, fields, methods, and relationships.' },
  { term: 'sequence diagram', definition: 'UML diagram that shows messages between participants over time.' },
  { term: 'state diagram', definition: 'UML diagram that shows possible states and transitions.' },
  { term: 'activity diagram', definition: 'UML diagram that shows workflow steps and decisions.' },
  { term: 'use case diagram', definition: 'UML diagram that shows actors and goals from a user perspective.' },
  { term: 'component diagram', definition: 'UML diagram that shows larger software parts and dependencies.' },
  { term: 'association', definition: 'UML relationship meaning one type knows about or uses another.' },
  { term: 'inheritance', definition: 'Object-oriented relationship where one class extends another.' }
];
