-- Auto-generated seed data (Kanto / first 151). Regenerate with generate-seed.mjs

TRUNCATE pokemon_type, pokemon RESTART IDENTITY CASCADE;

INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (1, 'bulbasaur', 7, 69, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (1, 1, 'grass');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (1, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (2, 'ivysaur', 10, 130, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (2, 1, 'grass');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (2, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (3, 'venusaur', 20, 1000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (3, 1, 'grass');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (3, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (4, 'charmander', 6, 85, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (4, 1, 'fire');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (5, 'charmeleon', 11, 190, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (5, 1, 'fire');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (6, 'charizard', 17, 905, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (6, 1, 'fire');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (6, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (7, 'squirtle', 5, 90, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (7, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (8, 'wartortle', 10, 225, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (8, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (9, 'blastoise', 16, 855, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (9, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (10, 'caterpie', 3, 29, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (10, 1, 'bug');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (11, 'metapod', 7, 99, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (11, 1, 'bug');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (12, 'butterfree', 11, 320, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (12, 1, 'bug');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (12, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (13, 'weedle', 3, 32, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (13, 1, 'bug');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (13, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (14, 'kakuna', 6, 100, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (14, 1, 'bug');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (14, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (15, 'beedrill', 10, 295, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (15, 1, 'bug');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (15, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (16, 'pidgey', 3, 18, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (16, 1, 'normal');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (16, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (17, 'pidgeotto', 11, 300, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (17, 1, 'normal');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (17, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (18, 'pidgeot', 15, 395, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (18, 1, 'normal');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (18, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (19, 'rattata', 3, 35, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (19, 1, 'normal');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (20, 'raticate', 7, 185, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (20, 1, 'normal');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (21, 'spearow', 3, 20, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (21, 1, 'normal');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (21, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (22, 'fearow', 12, 380, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (22, 1, 'normal');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (22, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (23, 'ekans', 20, 69, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (23, 1, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (24, 'arbok', 35, 650, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (24, 1, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (25, 'pikachu', 4, 60, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (25, 1, 'electric');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (26, 'raichu', 8, 300, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (26, 1, 'electric');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (27, 'sandshrew', 6, 120, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (27, 1, 'ground');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (28, 'sandslash', 10, 295, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (28, 1, 'ground');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (29, 'nidoran-f', 4, 70, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (29, 1, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (30, 'nidorina', 8, 200, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (30, 1, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (31, 'nidoqueen', 13, 600, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (31, 1, 'poison');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (31, 2, 'ground');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (32, 'nidoran-m', 5, 90, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (32, 1, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (33, 'nidorino', 9, 195, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (33, 1, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (34, 'nidoking', 14, 620, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (34, 1, 'poison');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (34, 2, 'ground');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (35, 'clefairy', 6, 75, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (35, 1, 'fairy');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (36, 'clefable', 13, 400, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (36, 1, 'fairy');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (37, 'vulpix', 6, 99, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (37, 1, 'fire');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (38, 'ninetales', 11, 199, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (38, 1, 'fire');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (39, 'jigglypuff', 5, 55, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (39, 1, 'normal');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (39, 2, 'fairy');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (40, 'wigglytuff', 10, 120, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (40, 1, 'normal');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (40, 2, 'fairy');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (41, 'zubat', 8, 75, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (41, 1, 'poison');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (41, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (42, 'golbat', 16, 550, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (42, 1, 'poison');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (42, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (43, 'oddish', 5, 54, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (43, 1, 'grass');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (43, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (44, 'gloom', 8, 86, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (44, 1, 'grass');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (44, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (45, 'vileplume', 12, 186, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (45, 1, 'grass');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (45, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (46, 'paras', 3, 54, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (46, 1, 'bug');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (46, 2, 'grass');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (47, 'parasect', 10, 295, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (47, 1, 'bug');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (47, 2, 'grass');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (48, 'venonat', 10, 300, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (48, 1, 'bug');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (48, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (49, 'venomoth', 15, 125, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (49, 1, 'bug');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (49, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (50, 'diglett', 2, 8, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (50, 1, 'ground');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (51, 'dugtrio', 7, 333, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (51, 1, 'ground');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (52, 'meowth', 4, 42, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (52, 1, 'normal');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (53, 'persian', 10, 320, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (53, 1, 'normal');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (54, 'psyduck', 8, 196, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (54, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (55, 'golduck', 17, 766, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (55, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (56, 'mankey', 5, 280, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (56, 1, 'fighting');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (57, 'primeape', 10, 320, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (57, 1, 'fighting');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (58, 'growlithe', 7, 190, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (58, 1, 'fire');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (59, 'arcanine', 19, 1550, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (59, 1, 'fire');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (60, 'poliwag', 6, 124, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (60, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (61, 'poliwhirl', 10, 200, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (61, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (62, 'poliwrath', 13, 540, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (62, 1, 'water');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (62, 2, 'fighting');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (63, 'abra', 9, 195, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (63, 1, 'psychic');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (64, 'kadabra', 13, 565, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (64, 1, 'psychic');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (65, 'alakazam', 15, 480, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (65, 1, 'psychic');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (66, 'machop', 8, 195, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (66, 1, 'fighting');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (67, 'machoke', 15, 705, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (67, 1, 'fighting');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (68, 'machamp', 16, 1300, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (68, 1, 'fighting');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (69, 'bellsprout', 7, 40, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (69, 1, 'grass');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (69, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (70, 'weepinbell', 10, 64, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (70, 1, 'grass');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (70, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (71, 'victreebel', 17, 155, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (71, 1, 'grass');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (71, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (72, 'tentacool', 9, 455, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (72, 1, 'water');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (72, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (73, 'tentacruel', 16, 550, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (73, 1, 'water');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (73, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (74, 'geodude', 4, 200, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (74, 1, 'rock');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (74, 2, 'ground');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (75, 'graveler', 10, 1050, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (75, 1, 'rock');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (75, 2, 'ground');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (76, 'golem', 14, 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (76, 1, 'rock');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (76, 2, 'ground');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (77, 'ponyta', 10, 300, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (77, 1, 'fire');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (78, 'rapidash', 17, 950, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (78, 1, 'fire');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (79, 'slowpoke', 12, 360, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (79, 1, 'water');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (79, 2, 'psychic');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (80, 'slowbro', 16, 785, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (80, 1, 'water');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (80, 2, 'psychic');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (81, 'magnemite', 3, 60, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (81, 1, 'electric');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (81, 2, 'steel');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (82, 'magneton', 10, 600, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (82, 1, 'electric');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (82, 2, 'steel');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (83, 'farfetchd', 8, 150, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (83, 1, 'normal');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (83, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (84, 'doduo', 14, 392, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (84, 1, 'normal');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (84, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (85, 'dodrio', 18, 852, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (85, 1, 'normal');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (85, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (86, 'seel', 11, 900, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (86, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (87, 'dewgong', 17, 1200, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (87, 1, 'water');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (87, 2, 'ice');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (88, 'grimer', 9, 300, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (88, 1, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (89, 'muk', 12, 300, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (89, 1, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (90, 'shellder', 3, 40, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (90, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (91, 'cloyster', 15, 1325, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (91, 1, 'water');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (91, 2, 'ice');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (92, 'gastly', 13, 1, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (92, 1, 'ghost');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (92, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (93, 'haunter', 16, 1, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (93, 1, 'ghost');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (93, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (94, 'gengar', 15, 405, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (94, 1, 'ghost');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (94, 2, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (95, 'onix', 88, 2100, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (95, 1, 'rock');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (95, 2, 'ground');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (96, 'drowzee', 10, 324, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (96, 1, 'psychic');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (97, 'hypno', 16, 756, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (97, 1, 'psychic');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (98, 'krabby', 4, 65, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (98, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (99, 'kingler', 13, 600, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (99, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (100, 'voltorb', 5, 104, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (100, 1, 'electric');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (101, 'electrode', 12, 666, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (101, 1, 'electric');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (102, 'exeggcute', 4, 25, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (102, 1, 'grass');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (102, 2, 'psychic');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (103, 'exeggutor', 20, 1200, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (103, 1, 'grass');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (103, 2, 'psychic');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (104, 'cubone', 4, 65, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (104, 1, 'ground');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (105, 'marowak', 10, 450, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (105, 1, 'ground');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (106, 'hitmonlee', 15, 498, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (106, 1, 'fighting');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (107, 'hitmonchan', 14, 502, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (107, 1, 'fighting');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (108, 'lickitung', 12, 655, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (108, 1, 'normal');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (109, 'koffing', 6, 10, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (109, 1, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (110, 'weezing', 12, 95, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (110, 1, 'poison');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (111, 'rhyhorn', 10, 1150, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (111, 1, 'ground');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (111, 2, 'rock');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (112, 'rhydon', 19, 1200, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (112, 1, 'ground');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (112, 2, 'rock');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (113, 'chansey', 11, 346, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (113, 1, 'normal');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (114, 'tangela', 10, 350, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (114, 1, 'grass');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (115, 'kangaskhan', 22, 800, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (115, 1, 'normal');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (116, 'horsea', 4, 80, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (116, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (117, 'seadra', 12, 250, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (117, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (118, 'goldeen', 6, 150, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (118, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (119, 'seaking', 13, 390, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (119, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (120, 'staryu', 8, 345, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (120, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (121, 'starmie', 11, 800, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (121, 1, 'water');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (121, 2, 'psychic');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (122, 'mr-mime', 13, 545, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (122, 1, 'psychic');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (122, 2, 'fairy');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (123, 'scyther', 15, 560, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (123, 1, 'bug');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (123, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (124, 'jynx', 14, 406, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (124, 1, 'ice');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (124, 2, 'psychic');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (125, 'electabuzz', 11, 300, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (125, 1, 'electric');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (126, 'magmar', 13, 445, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (126, 1, 'fire');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (127, 'pinsir', 15, 550, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (127, 1, 'bug');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (128, 'tauros', 14, 884, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (128, 1, 'normal');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (129, 'magikarp', 9, 100, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (129, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (130, 'gyarados', 65, 2350, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (130, 1, 'water');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (130, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (131, 'lapras', 25, 2200, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (131, 1, 'water');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (131, 2, 'ice');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (132, 'ditto', 3, 40, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (132, 1, 'normal');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (133, 'eevee', 3, 65, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (133, 1, 'normal');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (134, 'vaporeon', 10, 290, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (134, 1, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (135, 'jolteon', 8, 245, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (135, 1, 'electric');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (136, 'flareon', 9, 250, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (136, 1, 'fire');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (137, 'porygon', 8, 365, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (137, 1, 'normal');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (138, 'omanyte', 4, 75, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (138, 1, 'rock');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (138, 2, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (139, 'omastar', 10, 350, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (139, 1, 'rock');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (139, 2, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (140, 'kabuto', 5, 115, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (140, 1, 'rock');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (140, 2, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (141, 'kabutops', 13, 405, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (141, 1, 'rock');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (141, 2, 'water');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (142, 'aerodactyl', 18, 590, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (142, 1, 'rock');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (142, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (143, 'snorlax', 21, 4600, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (143, 1, 'normal');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (144, 'articuno', 17, 554, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (144, 1, 'ice');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (144, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (145, 'zapdos', 16, 526, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (145, 1, 'electric');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (145, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (146, 'moltres', 20, 600, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (146, 1, 'fire');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (146, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (147, 'dratini', 18, 33, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (147, 1, 'dragon');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (148, 'dragonair', 40, 165, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (148, 1, 'dragon');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (149, 'dragonite', 22, 2100, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (149, 1, 'dragon');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (149, 2, 'flying');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (150, 'mewtwo', 20, 1220, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (150, 1, 'psychic');
INSERT INTO pokemon (id, name, height_dm, weight_hg, sprite_url) VALUES (151, 'mew', 4, 40, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png');
INSERT INTO pokemon_type (pokemon_id, slot, type_name) VALUES (151, 1, 'psychic');
