spring:
  application:
    name: pokedex-api
  datasource:
    url: jdbc:postgresql://localhost:5432/pokedex
    username: pokedex
    password: pokedex_dev
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: public

server:
  port: 8082

pokedex:
  api-base-path: /api/pokemon
